---
- name: test
  hosts: cisco_nxos
  gather_facts: no
  tasks:
  - name: Gather all legacy facts
    cisco.nxos.nxos_facts:
      gather_subset: all
    register: result
  - debug:
      msg: result