---
- name: test
  hosts: cisco_nxos
  vars_files:
    - group_vars/vars.yaml
  gather_facts: no
  tasks:
    - name: test
      cisco.nxos.nxos_facts:
        gather_subset: all
      register: result
    - debug:
        msg: result